### ISSUE TITLE
Problem with python 3.8.5

### ISSUE THREAD

**Issue by ekluzek** [NCAR/manage_externals#161]
### Summary of Issue:

manage_externals dies when using python 3.8.5

### Expected behavior and actual behavior:

With python 3.8.5 manage_externals dies with an error " dictionary keys changed during iteration"

With other versions of python it works normally

### Steps to reproduce the problem (should include model description file(s) or link to publi c repository):

```
setenv PATH "/glade/work/djk2120/miniconda3/bin:${PATH}:"
./manage_externals/checkout_externals -S
```

### What is the changeset ID of the code, and the machine you are using:

This is manage externals in CTSM tag branch_tags/TRENDY-2019.n05_ctsm1.0.dev056

The merge commit log says this is...
ESMCI/manage_externals@fc5acda
cheyenne

### Screen output or log file showing the error message and context:

> (NPL) djk2120/trendy2021> setenv PATH "/glade/work/djk2120/miniconda3/bin:${PATH}:"
> (NPL) djk2120/trendy2021> which python
> /glade/work/djk2120/miniconda3/bin/python
> (NPL) djk2120/trendy2021> ./manage_externals/checkout_externals -S
> Processing externals description file : Externals.cfg
> Processing externals description file : Externals_CLM.cfg
> Processing externals description file : Externals_CISM.cfg
> Checking status of externals: clm, fates, dictionary keys changed during iteration
> (NPL) djk2120/trendy2021> pwd
> /glade/work/djk2120/trendy2021

**Comment by billsacks** [comment]
Is it possible that this is using an older version of manage_externals? An issue like this was fixed in https://github.com/ESMCI/manage_externals/pull/138 . It's possible that this is a different issue, but I think the first thing to check is whether you're using the latest version of manage_externals.

**Comment by billsacks** [comment]
Actually, I just looked at the manage_externals version you say you're using, and indeed it looks a few years old. So I think this is a fixed issue. I'm going to go ahead and close this, but feel free to reopen if you feel this is still an issue with the latest manage_externals.

This is a duplicate of https://github.com/ESMCI/manage_externals/issues/135

**Comment by ekluzek** [comment]
OK, I tried it in the most recent version of CTSM and it works fine. So you must be correct this is a duplicate of a resolved issue.
