### ISSUE TITLE
Github no longer supports SVN pulling repos

### ISSUE THREAD

**Issue by scotty110** [NCAR/manage_externals#211]
### Brief summary of bug

Trying to run `./manage_externals/checkout_external` but get an error that GitHub no longer supports SVN.

### General bug information

**CESM version you are using:release-cesm2.1.2** 

**Machine you are using:Docker on x86 Macbook** 

**Have you modified the code? (If so, please point us to you changes.): No** [Yes / No]

### Details of bug

When I run `./manage_externals/checkout_external` I get the below error message. Looks like it's an Github not supporting SVN issue? I am running python3.8

```#26 [22/22] RUN ./manage_externals/checkout_externals
#26 0.258 Processing externals description file : Externals.cfg (/opt/my_cesm_sandbox)
#26 0.260 Checking local status of required & optional components: cam, cice, cime, cism, clm, mosart, pop, rtm, ww3, 
#26 0.260 Checking out externals: cime, cam, Processing externals description file : Externals_CAM.cfg (/opt/my_cesm_sandbox/components/cam)
#26 40.28 Checking out externals: chem_proc, carma, clubb, cosp2, 
#26 50.61 ERROR: SVN access to github.com is no longer supported
#26 50.61 ERROR:root:SVN access to github.com is no longer supported
#26 ERROR: process "/bin/sh -c ./manage_externals/checkout_externals" did not complete successfully: exit code: 1
------
 > [22/22] RUN ./manage_externals/checkout_externals:
0.258 Processing externals description file : Externals.cfg (/opt/my_cesm_sandbox)
Processing externals description file : Externals_CAM.cfg (/opt/my_cesm_sandbox/components/cam)

50.61 ERROR: SVN access to github.com is no longer supported
50.61 ERROR:root:SVN access to github.com is no longer supported
```

### Steps to reproduce the problem. Include externals description file(s) and link to public repository

https://github.com/scotty110/CESM_CAM/tree/master

### Screen output or log file showing the error message and context

https://github.blog/2023-01-20-sunsetting-subversion-support/

**Comment by jedwards4b** [comment]
The fix that you need is in cesm2.1.5, please update to that version.

**Comment by scotty110** [comment]
Thank you so much! Solve my issue

**Comment by sally-xiyue** [comment]
Hello, I'm experiencing this issue while trying to download release-cesm2.1.5 and release-cesm2.2.2. Is there still a way to download CESM2? Thank you!
